fix: correct edge values of window_bits
bicycle1885/CodecZlib.jl pull request #60
Opened 2022-03-25 07:40 UTC by f3fora

see https://docs.python.org/3/library/zlib.html

2023-01-24 09:53 UTC, mkitti commented
I'm not clear if this agrees with https://www.zlib.net/manual.html

2025-01-06 01:40 UTC, nhz2 requested changes

2025-01-06 01:40 UTC, nhz2 commented on src/compression.jl
> +- `windowbits`: size of history buffer (9..15) or (-15..-9)
```suggestion
- `windowbits`: size of history buffer (9..15)
```

2025-01-06 01:40 UTC, nhz2 commented on src/compression.jl
> +        throw(ArgumentError("|windowbits| must be within 9..15"))
```suggestion
    elseif !(9 ≤ windowbits ≤ 15)
        throw(ArgumentError("windowbits must be within 9..15"))
```

2025-01-06 01:40 UTC, nhz2 commented on src/decompression.jl
> +- `windowbits`: size of history buffer (8..15) or (-15..-8) or 0
```suggestion
- `windowbits`: size of history buffer (8..15)
```

2025-01-06 01:40 UTC, nhz2 commented on src/decompression.jl
> +        throw(ArgumentError("|windowbits| must be within 8..15 or 0"))
```suggestion
    if !(8 ≤ windowbits ≤ 15)
        throw(ArgumentError("windowbits must be within 8..15"))
```

2025-01-06 01:40 UTC, nhz2 commented on src/compression.jl
> +- `windowbits`: size of history buffer (9..15) or (-15..-9)
Negative window values are used to signal raw deflate format instead of zlib format in the libzlib C library. Here raw deflate is signaled by using `DeflateCompressor`.

2025-01-06 01:40 UTC, nhz2 commented on src/decompression.jl
> +- `windowbits`: size of history buffer (8..15) or (-15..-8) or 0
I don't think there is a need to support the `windowbits == 0` option, it is allowed in libzlib, but I'm not sure what a practical use for this option is.

> windowBits can also be zero to request that inflate use the window size in the zlib header of the compressed stream.

2025-01-06 18:10 UTC, nhz2 commented
The[ zlib manual section](https://www.zlib.net/manual.html#Advanced) on `deflateInit2`  is not straight forward about `windowbits=8` 

> The windowBits parameter is the base two logarithm of the window size (the size of the history buffer). It should be in the range 8..15 for this version of the library. Larger values of this parameter result in better compression at the expense of memory usage. The default value is 15 if deflateInit is used instead.

> For the current implementation of deflate(), a windowBits value of 8 (a window size of 256 bytes) is not supported. As a result, a request for 8 will result in 9 (a 512-byte window). In that case, providing 8 to inflateInit2() will result in an error when the zlib header with 9 is checked against the initialization of inflate(). The remedy is to not use 8 with deflateInit2() with this initialization, or at least in that case use 9 with inflateInit2().

I think `windowbits=8` was originally intended to work, but there is a bug in zlib so now it isn't allowed.

Ref: https://github.com/madler/zlib/issues/737 https://github.com/madler/zlib/issues/171

2025-01-06 18:28 UTC, nhz2 commented
I'm going to merge this now to be able to move forward on some other issues, but @mkitti and @f3fora please open an issue if there are any problems with this change, or if you need support for other advanced zlib configuration options.

2025-01-06 18:29 UTC, merged